server:
  ssl:
    key-store: classpath:keystore/authgateway.p12
    key-password: password
    key-store-type: pkcs12
    key-alias: authgateway
    key-store-password: password
    enabled: true
  port: 8443
  servlet:
    context-path: /authgateway
spring:
  application:
    name: authgateway
  jackson:
    serialization:
      write-dates-as-timestamp: false
      time-zone: Europe/Berlin
      date-format: yyyy-MM-dd
    autoconfiguration:
      exclude: org.springframework.boot.autoconfigure.ampq.RabbitAutoConfiguration
    datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
        hibernate:
          ddl-auto: update
    h2:
      console:
        enabled: true
        path: /h2
logging:
  file:
    name: ./logs/authgateway.log
    max-size: 10MB
  pattern:
    console: "%d %-5level %logger : %msg%n%"
    file: "%-5level [%date] [%thread] %logger - %msg%n"
  level:
    root: DEBUG
      org.springframework.web: DEBUG
      com.auth.authgateway: DEBUG
      org.hibernate: DEBUG
config:
  publicKey:
    --------BEGIN PUBLIC KEY-------
    -------- END PUBLIC KEY--------


