server:
  port: 8765
spring:
  application:
    name: CLOUDCONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gajanan-kharat/cloud-config-server
          clone-on-start: true